### ISSUE TITLE
NullPointerException when trying to use !song

### ISSUE THREAD

**Issue by Klocko** [joelamos/SourceRadio#11]
java.lang.NullPointerException
at com.joelchristophel.sourceradio.Playlist.handleNewInput(Playlist.java:228)
at com.joelchristophel.sourceradio.LogReader$1.run(LogReader.java:96)
at java.lang.Thread.run(Unknown Source)

I've tried everything, no idea what's going on D:

I have tried the command in
- A local server
- Server with other players
(Nobody had the same name, and the chat is not affected by a plugin.)

**Comment by joelamos** [comment]
In /SourceRadio/libraries/, what is the exact file size of youtube-dl.exe?

**Comment by Klocko** [comment]
v2017.01.29

youtube-dl.exe is at 7,447 KB, I'm gonna see if the problem's resolved itself.

**Comment by Klocko** [comment]
It worked! When it was erroring, I think I remember youtube-dl being 3,447 KB. Probably just my horrible memory, though.

No idea why it errored before, maybe the youtube-dl was partially downloaded.

**Comment by joelamos** [comment]
Yes, that's my suspicion.
