### ISSUE TITLE
Exception in main thread.

### ISSUE THREAD

**Issue by Tytanium-YT** [joelamos/SourceRadio#14]
Exception details:

    `Exception in thread "main" java.lang.NullPointerException
          at com.jeolchristopel.sourceradio.Game.getCfgPath(Game.java:96)
          at com.jeolchristopel.sourceradio.ScriptWriter.writeScripts(scriptWriter.java:39)
          at com.jeolchristopel.sourceradio.Playlist.intialize(Playlist.java:172)
          at com.jeolchristopel.sourceradio.Playlist.<init>(Playlist.java:158)
          at com.jeolchristopel.sourceradio.Playlist.getInstance(Playlist.java:139)
          at ``com.jeolchristopel.sourceradio.Playlist.main(Playlist.java:97)`

Yes, I did install it correctly.
Also, why do you need 2 initialization functions?
(You can tell I only know C++ can't you ;P)

**Comment by joelamos** [comment]
Is this the full error log? Do you have your game in a custom location?

**Comment by Tytanium-YT** [comment]
It's everything that appeared in the console window.
No i do not have the game in a custom location.

**Comment by joelamos** [comment]
What game are you playing?

**Comment by Tytanium-YT** [comment]
TF2

**Comment by joelamos** [comment]
So then you have the directory `C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\cfg`?

**Comment by Tytanium-YT** [comment]
Yes

**Comment by joelamos** [comment]
Have you changed the `steam path` property in `properties.txt`?

**Comment by Tytanium-YT** [comment]
Where would that be located?
I didn't see anything to do with that in the installer?

**Comment by joelamos** [comment]
`SourceRadio/properties/properties.txt`

**Comment by Tytanium-YT** [comment]
Ok, what do I need to change? ;P

**Comment by joelamos** [comment]
What is the value of that property?

**Comment by Tytanium-YT** [comment]
C:\Program Files (x86)\Steam

**Comment by joelamos** [comment]
You definitely are using your C drive?

**Comment by Tytanium-YT** [comment]
Yes, it is the only drive connected to my computer.

**Comment by joelamos** [comment]
Nothing to change in that file then.

**Comment by joelamos** [comment]
Actually, maybe there is. Enter your Steam profile URL [here](https://steamid.io/lookup) to find your SteamID3, and paste that into the properties file.

**Comment by Tytanium-YT** [comment]
Done. ran the program again.
Same exception.

**Comment by joelamos** [comment]
Are you sure you're running the latest update? The line numbers in the error log don't seem to match up exactly with the code.

**Comment by Tytanium-YT** [comment]
I downloaded it from gamebanana, so, probably not.
I'll be installing it from github now lol.

**Comment by joelamos** [comment]
GameBanana is the correct place to download it from. What version appears in the program console when you run it?

**Comment by Tytanium-YT** [comment]
2017.02.03

**Comment by joelamos** [comment]
Okay, so you're running the latest version.

**Comment by joelamos** [comment]
I notice that you did some modifications to the error log. (e.g. my name's spelled wrong) Why was that?

**Comment by Tytanium-YT** [comment]
Sorry! I have dyslexia :(

**Comment by Tytanium-YT** [comment]
I'll check if I did anything else wrong like that.

**Comment by joelamos** [comment]
Oh so you typed it out from the console by hand rather than copying?

**Comment by Tytanium-YT** [comment]
I was unable to copy and paste.

**Comment by Tytanium-YT** [comment]
![capture](https://cloud.githubusercontent.com/assets/22021401/22858361/ffe1df1a-f10e-11e6-90a9-caa13b42526c.PNG)
There is a screenshot of the console.

**Comment by Tytanium-YT** [comment]
I'm just going to try reinstalling.

**Comment by Tytanium-YT** [comment]
Ayyy! I works! Thanks for all the help :)

**Comment by joelamos** [comment]
Hmm, that's weird, but I'll take it! Glad it works and have fun. Also, feel free to star the repository if you like it.

**Comment by Tytanium-YT** [comment]
:)

**Comment by Klocko** [comment]
Reopening because I'm getting this too. I only have a C drive.
