### ISSUE TITLE
Buttons repeatedly unbind

### ISSUE THREAD

**Issue by QuadraJACS** [joelamos/SourceRadio#15]
I've uninstalled my copy of SourceRadio (poor install ruined everything, intending to re-install later) and now my game repeatedly unbinds certain keys (Spacebar, B, the left arrow, and M to be specific) for apparently no reason. 

It only happens when I turn the game off and back on. Rebinding the keys keeps them working for the rest of the session.

Is there any way I can make this stop happening?

**Comment by joelamos** [comment]
Sorry for your troubles. Go to `tf\cfg\autoexec.cfg` and remove the line `exec sourceradio.cfg`.

**Comment by QuadraJACS** [comment]
Thanks. Sorry it took me way too long to respond, I don't check my email
often and it likes to hide things from me.
