### ISSUE TITLE
Could not log in to the MySQL server. 

### ISSUE THREAD

**Issue by Sario64** [joelamos/SourceRadio#3]
I checked my credentials and they're exactly where the mysql.exe is located and for some reason when I request a song, Tftune  stops working and the commands won't work anymore

**Comment by joelamos** [comment]
What does the command prompt print out when you run the .bat file? (If it closes too quickly for you to be able to see, edit the bat file and add cmd /k to the last line.)

**Comment by Sario64** [comment]
C:\Program Files (x86)\TFTunes>java -jar TFTunes.jar
**Running TFTunes**
Could not log in to the MySQL server. Check your credentials and try again or continue to run TFTunes without a database.
Owner: Me
Admins: another admin, etc, an admin's username goes here
Listening for commands...

**Comment by Sario64** [comment]
It was working fine but then I tried to update it and this started happening

**Comment by joelamos** [comment]
Have you downloaded xampp? If so, are you using the default root user with no password?

You also mentioned that TFTunes isn't working in general. However, TFTunes is supposed to work without a database, so it's probably a separate issue. Please post the error message you get when you try to request a song.

**Comment by Sario64** [comment]
mysql path -> C:\xampp\mysql\bin
mysql server -> localhost
mysql user -> root
mysql password -> 
I'm pretty sure everything is where it should be, maybe I can try reinstalling xampp.

I'm not getting an error message for it, it will recognize other commands, but after I try !song no music comes and I've waited patiently for it, but after that it won't recognize anymore commands

**Comment by Sario64** [comment]
wait, it just started working again

**Comment by joelamos** [comment]
Both the database and commands?

**Comment by Sario64** [comment]
suddenly the music started to play while I was youtube, maybe its just really delayed for me, I don't know about the database, I'm gonna restart it and check

**Comment by joelamos** [comment]
If you add me on Steam, I'd join a server with you sometime to help you test things out.

**Comment by Sario64** [comment]
The database isn't working still
I'm gonna try the commands

That sounds good, whats your username?

**Comment by joelamos** [comment]
Click the link above ^

**Comment by Sario64** [comment]
how long does it usually take for a request to play?

**Comment by joelamos** [comment]
2 seconds or seconds. Due to the bug I mentioned earlier, I'd recommend restating your computer to kill all related processes and then starting up TFTunes before TF2. When the next version arrives, you'll be able to start up TFTunes whenever.
