### ISSUE TITLE
Something breaks the program + Extra Issue

### ISSUE THREAD

**Issue by UltimaTheHawke** [joelamos/SourceRadio#4]
Hello there,
Just saying I really love the program, gets everyone together and such, but there's this really big issues where after a few minutes (or even seconds), this error spews out and nothing works from then on.

java.lang.NullPointerException
        at com.joelchristophel.sourceradio.Playlist.isAdmin(Playlist.java:655)
        at com.joelchristophel.sourceradio.Playlist.handleNewInput(Playlist.java:156)
        at com.joelchristophel.sourceradio.LogReader$1.run(LogReader.java:103)
        at java.lang.Thread.run(Unknown Source)

There's also another issue where, on lots of servers I go on, admins and such are unable to control the music to due their [Admin] tag in their name. Is there any way to circumvent this or will it be in the next update?

Thanks,
~Chaotix_

**Comment by UltimaTheHawke** [comment]
Yes, it's the latter; I have to use their name instead of their SteamID because the server automatically puts on the [Admin] tag on the user. It's worked for other admins, but some of them are unable to skip songs. I'll send a copy of the console.log when I have time.

I'll also try your temporary fix for now as well; if it doesn't work I'll respond back.

**Comment by joelamos** [comment]
I can't be positive without a log, but I'm guessing that when admins send a message, it shows up in the log like this "[Admin] Cool Guy42 : !song darude sandstorm". This is a problem because as a normal user, I set my username to [Admin] Cool Guy42, so I can't always assume that I should just cut off "[Admin]" from the beginning of usernames.

What do you mean when you say "I have to use their name instead of their SteamID?"

**Comment by UltimaTheHawke** [comment]
Hello.

For some reason, I can't use any admin commands. I'd figure I'd add it to this thread.

I get no errors, it's just not working at all.

Also, the fix did work until it broke... again. :P

**Comment by joelamos** [comment]
Thanks for reporting. I'll add a comment to that line explaining it should be kept at the bottom.

**Comment by Klocko** [comment]
I'm getting the exact same java error too, the chat isn't changed by the server at all. Tried on a local server and online with other players, nobody has the same name.

**Comment by joelamos** [comment]
Could you open a new issue with that?
