### ISSUE TITLE
Output device name is null

### ISSUE THREAD

**Issue by ThornieTheBeard** [joelamos/SourceRadio#5]
Hey there, I'm new to this program and I've gotten this error:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at CSCore.SoundOut.WasapiOut.set_Device(MMDevice value)
   at AudioController.AudioController.ChooseOutput(String nameFragment)
   at AudioController.AudioController.Main(String[] args)
```

Is there something I can do to fix this? If it's really simple please help anyway because I Don't usually do programming myself so I am struggling right now!

**Comment by joelamos** [comment]
Thanks for reporting this. I recently had another user report the same issue, although this doesn't affect all users.

I'm still trying to figure out the cause, and any information you provide me with will help me to do so.

What version of Windows are you running?

**Comment by ThornieTheBeard** [comment]
Thanks for the temp fix! It's works :P
